### PR TITLE
fix #118

### LINKED ISSUE #118: add methods for mapping collection to inner elements
add something like

collection.all('//div') => finds all div's in each element
collection.map('//div') => find first div in each element, fail if can't find

### PR DESCRIPTION
**Pull request by alex-popov-tech**

### CODE REVIEW

File: lib/locators/elementInEachByLocator.ts [hunk 1]
```diff
@@ -0,0 +1,42 @@
...
+    ) {
+        this.by = by;
+        this.collection = collection;
+    }
+
+    async find(): Promise<WebElement[]> {
+        const rootElements = await this.collection.getWebElements();
+        const innerElements = [];
+        for (const rootElement of rootElements) {
+            innerElements.push(await rootElement.findElement(this.by));
```
Comment (yashaka) [inline lib/locators/elementInEachByLocator.ts]: here we have a call to findElement that might fail... for sure we need a test for it, and ensure that error message is adequate...
